<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">


<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ja" lang="ja">
<head>
<meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
<title>Amazon Suggestion</title>
<meta name="robots" content="noindex,nofollow">
<noscript><meta http-equiv="Refresh" content="0;URL=http://nexesjapan.com/contents/member/error.html"></noscript>
<script type="text/javascript" src="is_login.php"></script>

<script src="js/jquery.min.js"></script>
<script src="js/jquery-ui.min.js"></script>
<link rel="stylesheet" type="text/css" href="css/tooltipster.css" />
<script src="js/zaichu.js"></script>
<script src="js/zaichu2.js"></script>
<script src="js/store.js"></script>

<script src="js/jquery.tooltipster.min.js"></script>
<link rel="stylesheet" href="css/jquery-ui.css" />
<link rel="stylesheet" href="css/zaichu.css" />
<link rel="stylesheet" href="css/zaichu2.css" />

<style type="text/css">
.css_btn_class {
  
  font-size:10px;
  font-family:Arial;
  font-weight:normal;
  -moz-border-radius:6px;
  -webkit-border-radius:6px;
  border-radius:6px;
  border:1px solid #ededed;
  padding:7px 12px;
  text-decoration:none;
  background:-moz-linear-gradient( center top, #dfdfdf 5%, #ededed 100% );
  background:-ms-linear-gradient( top, #dfdfdf 5%, #ededed 100% );
  filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#dfdfdf', endColorstr='#ededed');
  background:-webkit-gradient( linear, left top, left bottom, color-stop(5%, #dfdfdf), color-stop(100%, #ededed) );
  background-color:#ededed;
  color:#777777;
  display:inline-block;
  margin-top: 8px;
}.css_btn_class:hover {
    background:-moz-linear-gradient( center top, #ededed 5%, #ededed 100% );
      background:-ms-linear-gradient( top, #ededed 5%, #ededed 100% );
      filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#ededed', endColorstr='#ededed');
        background:-webkit-gradient( linear, left top, left bottom, color-stop(5%, #ededed), color-stop(100%, #ededed) );
        background-color:#ededed;
        }.css_btn_class:active {
  position:relative;
  top:1px;
}
/* This css button was generated by css-button-generator.com */
</style>
<script language="javascript">
<!--

$(function(){
	$('.tooltip').tooltipster();
   

	ShowLength(document.getElementById('t_box').value);
	
	//for (i = 0; i < BANLIST.length; i++) {
	//
	//	document.getElementById('banlist').value += BANLIST[i]+"\r\n";
	//}
	init_banlist();
	init_savetext();
});

// --></script>
</head>
<body style="background-color:#ccc;">
<form name="fm" method="post">
<textarea type=text name='t_box' id='t_box' style='width:100%;' rows=4 onkeyup='ShowLength(value);' ></textarea>
<br/>
<button type="button" onClick="document.getElementById('t_box').value='';ShowLength('');" class="tootip css_btn_class" title="テキストエリア内を消去します">クリアー</button>
<button type="button" onClick="DelSP();ShowLength(document.getElementById('t_box').value);" class="tootip css_btn_class" title="全角スペース→半角スペースに変換、連続したスペースをまとめ、両端のスペースを除去します">スペース整形</button>
<button type="button" onClick="CVT_KANA();" class="tootip css_btn_class" title="全てひらがな文字をカタカナに変換+全角英数字を半角英数字に変換。例(あい→アイ、ゆずレモン→ゆずレモン、1２3４5→12345)">文字統一(あ>ア １>1)</button>
<button type="button" onClick="DEL_BANLIST();" id="cmd_delbanlist" class="tootip css_btn_class" title="">禁止キーワード削除</button>
<button type="button" onClick="DelKey();ShowLength(document.getElementById('t_box').value);" class="css_btn_class tootip" title="テキストエリア内の重複キーワードを取り除きます(改行も取り除かれますので注意してください)">重複削除(改行が取り除かれます)</button>
&nbsp&nbsp
<select name="maxrow" id="maxrow">
    <option value="50b" selected="selected">50バイトで折り返し</option>
    <option value="2000b">2000バイトで折り返し</option>
    <option value="2">2行に最適化</option>
    <option value="3">3行に最適化</option>
    <option value="4">4行に最適化</option>
    <option value="5">5行に最適化</option>
	
</select>
<button type="button" onClick="KeySort();" class="tootip css_btn_class" title="キーワードを指定した行で均等並べします。5行なら250bytes以下を目安で使用してください(キーワード構成によっては一行50bytesを超えます)">キーワード並び替え</button>
&nbsp&nbsp
<input type="text" size=10 maxlength=20 id="delkywd" name="delkywd" value="">
<button type="button" onClick="DEL_Keyword(document.getElementById('delkywd').value);DelSP();ShowLength(document.getElementById('t_box').value);" class="css_btn_class tootip" title="指定キーワードをテキストエリアより完全に削除します。">指定キーワード完全削除</button>
</form>

<!--テキストエリア保存-->
<div style="margin:5px;">
<select name="select_savename" id="select_savename" onchange="select_savename_change()">
</select>
<input type="text" size=10 maxlength=20 id="text_save" name="text_save" value="">
<button type="button" onClick="lord_Txtarea();" class="tootip css_btn_class" title="">読込</button>
<button type="button" onClick="save_Txtarea();" class="tootip css_btn_class" title="">保存</button>
</div><br>

<div style="margin:5px;">
<div><span id="maxrows">0行</span></div>
<div class="ilt"><button type="button" onClick="Select_Txtarea(document.getElementById('t_box'),1);" class="tootip css_btn_class" title="">1行目</button><span id="inputlength0">0bytes</span></div>
<div class="ilt"><button type="button" onClick="Select_Txtarea(document.getElementById('t_box'),2);" class="tootip css_btn_class" title="">2行目</button><span id="inputlength1">0bytes</span></div>
<div class="ilt"><button type="button" onClick="Select_Txtarea(document.getElementById('t_box'),3);" class="tootip css_btn_class" title="">3行目</button><span id="inputlength2">0bytes</span></div>
<div class="ilt"><button type="button" onClick="Select_Txtarea(document.getElementById('t_box'),4);" class="tootip css_btn_class" title="">4行目</button><span id="inputlength3">0bytes</span></div>
<div class="ilt"><button type="button" onClick="Select_Txtarea(document.getElementById('t_box'),5);" class="tootip css_btn_class" title="">5行目</button><span id="inputlength4">0bytes</span></div>
<div>以降合計<span id="inputlength5">0bytes</span></div>
</div><br>

<div style="margin:5px;">
<br>
<br>
禁止キーワードリスト
<textarea type=text name='banlist' id='banlist' style='width:100%;' rows=10 ></textarea>
<button type="button" onClick="save_banlist();" class="tootip css_btn_class" title="禁止キーワードリストを一時保存します。次回読み込み時は自動ロードされます。リストはこのPCへ保存されます">保存</button>
<button type="button" onClick="clear_banlist();" class="tootip css_btn_class" title="禁止キーワードリストを消します。">消去</button>
<button type="button" onClick="ini_banlist();" class="tootip css_btn_class" title="禁止キーワードリストを初期状態に戻します">デフォルトへ戻す</button>


</div><br>


<form name="delkey" method="post">
<input type="hidden" id="i_hidden" name="i_hidden" >
</form>
<br>

</body>
</html>
